Repository dotnet-architecture/eShopOnContainers, pull requests merged in 2020-08, with the labels that each got.

#1373 Removed unused usings from ModelDTOs
  src/Web/WebMVC/Services/ModelDTOs/LocationDTO.cs
  src/Web/WebMVC/Services/ModelDTOs/OrderDTO.cs
  src/Web/WebMVC/Services/ModelDTOs/OrderProcessAction.cs
Labels: Refactoring

#1382 Bump dot-prop from 4.2.0 to 5.1.1 in /src/Web/WebSPA
  src/Web/WebSPA/package-lock.json
Labels: dependencies

#1372 Updated readme.md with mslearn link
  README.md
Labels: backlog-item

#1396 Updated serialize-javascript version to 3.1.0
  src/Web/WebSPA/package-lock.json
Labels: update-version

#1398 Updated "minimist" version to 1.2.5
  src/Web/WebSPA/package-lock.json
Labels: update-version
